# BedWars1058Cosmetics v1.0.0

# Gives player cosmetics item on join
on-join-items:
  # Enabled?
  enabled: true
  # Name of item (Color codes are supported)
  name: "&6Cosmetics &7(Right click)"
  # Item type (Requires Material name, press F3 + H and hover your mouse on a item for Material name)
  # Examples : CHEST, COMPASS, NETHER_STAR and ...
  item: CHEST
  # Item slot in hand, from 1 (first item from left) to 9 (last item at end)
  slot: 5
  # Lore of item, (Color codes are supported)
  lore:
    - "&6Right click for cosmetics"

# Cosmetics menu items
CosmeticsMenu:
  # Title of menu
  title: "&aCosmetics"
  # Items
  items:
    # Close item
    close:
      # Item type (Requires Material name, press F3 + H and hover your mouse on a item for Material name)
      # Examples : BARRIER, COMPASS, NETHER_STAR and ...
      name: "&cClose"
      # Item Material
      item: BARRIER
      # Lore of item, (Color codes are supported)
      lore:
        - "&7Click for close this menu"
    back:
      name: "&bBack"
      item: ARROW
      lore:
        - "&7Click for back to previous menu"
    bedBreakEffects:
      name: "&bBed Break Effects"
      item: BED
      lore:
        - "&7Click for open bed break effects menu"
    deathCries:
      name: "&6Death cries"
      item: BLAZE_POWDER
      lore:
        - "&7Click for open death cries menu"

BedBreakEffectsMenu:
  title: "&bBed Break Effects"
  cosmetics:
    fireworkEffect:
      enabled: true
      name: "&bBed Break Effects"
      item: FIREWORK
      lore:
        - "&7Right click for preview of effect"

DeathCriesMenu:
  title: "&6Death Cries"
  cosmetics:
    catCry:
      enabled: true
      name: "&bCat Cry"
      item: BED
      lore:
        - "&7Right click for preview of sound"

messages:
  no-permission: "&cYou don't have permission."
  not-enough-arguments: "&cPlease enter a valid argument."
  unknown-argument: "&cUnknown argument."
  invalid-executor: "&cThis command can only be executed by a player."
  reload: "&bBedWars1058Cosmetics &6has been reloaded."